In [2]:
import numpy as np
import torch
import random

In [3]:
#record1
state1 = np.array([[-1.,  1., -1.],
                                           [ 0.,  1.,  0.],
                                           [ 0.,  0.,  0.]])
v1=1.0
p1=torch.tensor([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.])
count_exp1 = 0

#record2
state2 = np.array([[-1.,  0., -1.],
                                           [ 0.,  1.,  0.],
                                           [ 0.,  0.,  0.]])
v2=-1.0
p2=torch.tensor([ 0.5,  0.5,  0.,  0.,  0.,  0.,  0.,  0.,  0.])
count_exp2 = 0



In [4]:
hash_state1 = tuple(map(tuple, state1)) 
hash_state2 = tuple(map(tuple, state2)) 

In [5]:
new_dict = {}

In [6]:
new_dict[hash_state1] = (v1, p1, count_exp1)
new_dict[hash_state2] = (v2, p2, count_exp2)

In [7]:
new_dict

{((-1.0, 1.0, -1.0), (0.0, 1.0, 0.0), (0.0, 0.0, 0.0)): (1.0,
  tensor([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.]),
  0),
 ((-1.0, 0.0, -1.0), (0.0, 1.0, 0.0), (0.0, 0.0, 0.0)): (-1.0,
  tensor([ 0.5000,  0.5000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000]),
  0)}

In [8]:
a = new_dict.items()

In [9]:
a

dict_items([(((-1.0, 1.0, -1.0), (0.0, 1.0, 0.0), (0.0, 0.0, 0.0)), (1.0, tensor([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.]), 0)), (((-1.0, 0.0, -1.0), (0.0, 1.0, 0.0), (0.0, 0.0, 0.0)), (-1.0, tensor([ 0.5000,  0.5000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000]), 0))])

In [10]:
b = random.sample (a, 2)

In [11]:
b[0]

(((-1.0, 0.0, -1.0), (0.0, 1.0, 0.0), (0.0, 0.0, 0.0)),
 (-1.0,
  tensor([ 0.5000,  0.5000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000]),
  0))

In [12]:
b[0][0]

((-1.0, 0.0, -1.0), (0.0, 1.0, 0.0), (0.0, 0.0, 0.0))

In [58]:
samples = [(((0.0, 0.0, -1.0), (1.0, 0.0, 0.0), (1.0, -1.0, 0.0)), (1.0, torch.tensor([ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]), 2)), (((1.0, 0.0, 1.0), (-1.0, 0.0, 0.0), (0.0, -1.0, 0.0)), (1.0, torch.tensor([ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]), 2)), (((0.0, -1.0, -1.0), (0.0, 1.0, 0.0), (1.0, -1.0, 1.0)), (1, torch.tensor([ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]), 1))]

In [59]:
samples

[(((0.0, 0.0, -1.0), (1.0, 0.0, 0.0), (1.0, -1.0, 0.0)),
  (1.0, tensor([ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]), 2)),
 (((1.0, 0.0, 1.0), (-1.0, 0.0, 0.0), (0.0, -1.0, 0.0)),
  (1.0, tensor([ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]), 2)),
 (((0.0, -1.0, -1.0), (0.0, 1.0, 0.0), (1.0, -1.0, 1.0)),
  (1, tensor([ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]), 1))]

In [94]:
new_list = [torch.tensor([e[0]], dtype=torch.float,
            device=device) for e in samples if e is not None]

In [95]:
len(new_list)

3

In [96]:
all_states = torch.stack(new_list)

In [97]:
all_states

tensor([[[[ 0.,  0., -1.],
          [ 1.,  0.,  0.],
          [ 1., -1.,  0.]]],


        [[[ 1.,  0.,  1.],
          [-1.,  0.,  0.],
          [ 0., -1.,  0.]]],


        [[[ 0., -1., -1.],
          [ 0.,  1.,  0.],
          [ 1., -1.,  1.]]]])

In [85]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
all_v = torch.stack([torch.tensor([e[1][0]], dtype=torch.float,
            device=device) for e in samples])

In [86]:
sample_0 = samples[0]

In [87]:
sample_0[1][0]

1.0

In [88]:
all_v

tensor([[ 1.],
        [ 1.],
        [ 1.]])

In [47]:
all_states = torch.tensor(
    np.vstack([[[e[0]] for e in samples if e is not None]]),
    dtype=torch.float,
    device=device,
)

In [48]:
all_states

tensor([[[[ 0.,  0., -1.],
          [ 1.,  0.,  0.],
          [ 1., -1.,  0.]]],


        [[[ 1.,  0.,  1.],
          [-1.,  0.,  0.],
          [ 0., -1.,  0.]]],


        [[[ 0., -1., -1.],
          [ 0.,  1.,  0.],
          [ 1., -1.,  1.]]]])

In [69]:
all_v = torch.tensor(
            np.vstack([e[1][0] for e in samples if e is not None]),
            dtype=torch.float,
            device=device,
        )

In [70]:
all_v

tensor([[ 1.],
        [ 1.],
        [ 1.]])

In [98]:
samples = [(((-0.0, -0.0, -1.0), (-0.0, -0.0, 1.0), (-0.0, -0.0, -1.0)), (0.3333333333333333, torch.tensor([ 0.3333,  0.0000,  0.0000,  0.3333,  0.0000,  0.0000,  0.3333,
         0.0000,  0.0000]), 3)), (((-1.0, -0.0, 1.0), (-0.0, -1.0, 1.0), (-0.0, -1.0, -0.0)), (1, torch.tensor([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]), 1)), (((1.0, -1.0, -1.0), (-1.0, 1.0, 1.0), (0.0, 1.0, -1.0)), (0, torch.tensor([ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.]), 1))]

In [107]:
all_states = torch.stack([torch.tensor([e[0]], 
                                       dtype=torch.float,
                                       device=device) 
                          for e in samples if e is not None])

all_v = torch.stack([torch.tensor([e[1][0]],
                                  dtype=torch.float,
                                  device=device) 
                     for e in samples])

all_p = torch.stack([e[1][1] for e in samples])


In [108]:
all_states

tensor([[[[-0., -0., -1.],
          [-0., -0.,  1.],
          [-0., -0., -1.]]],


        [[[-1., -0.,  1.],
          [-0., -1.,  1.],
          [-0., -1., -0.]]],


        [[[ 1., -1., -1.],
          [-1.,  1.,  1.],
          [ 0.,  1., -1.]]]])

In [109]:
all_v

tensor([[ 0.3333],
        [ 1.0000],
        [ 0.0000]])

In [110]:
all_p

tensor([[ 0.3333,  0.0000,  0.0000,  0.3333,  0.0000,  0.0000,  0.3333,
          0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  1.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  1.0000,
          0.0000,  0.0000]])