# Dirichlet Noise

In [1]:
import numpy as np
import torch
torch.set_default_dtype(torch.float32)


probs = torch.tensor((0.1, 0.1, 0.3, 0.2, 0.05, 0.05, 0.2))

dir_eps = 0.25
dir_alpha = 1.0

In [104]:
noise = np.random.dirichlet([dirAlpha] * len(probs))

In [105]:
noise = torch.tensor(noise).type(torch.FloatTensor)

In [94]:
noise

tensor([ 0.3493,  0.1653,  0.0757,  0.0253,  0.2317,  0.0147,  0.1380])

In [95]:
noise.sum()

tensor(1.)

In [99]:
prob = (1-eps) * probs + eps * noise

In [100]:
prob

tensor([ 0.1623,  0.1163,  0.2439,  0.1563,  0.0954,  0.0412,  0.1845])

In [101]:
prob.sum()

tensor(1.)

In [97]:
eps * noise

tensor(1.00000e-02 *
       [ 8.7326,  4.1321,  1.8932,  0.6333,  5.7917,  0.3683,  3.4489])

In [98]:
(1-eps) * probs

tensor([ 0.0750,  0.0750,  0.2250,  0.1500,  0.0375,  0.0375,  0.1500])

In [2]:
probs = torch.tensor((0.1, 0.1, 0.3, 0.2, 0.05, 0.05, 0.2))

In [4]:
noise = torch.distributions.Dirichlet(torch.tensor([dir_alpha] * len(probs))).sample()

In [6]:
prob = (1-dir_eps) * probs + dir_eps * noise

In [7]:
prob

tensor([ 0.1565,  0.0769,  0.2427,  0.2289,  0.0658,  0.0540,  0.1753])

In [8]:
prob.sum()

tensor(1.)