# Creation of a boolean mask for illegal actions

In [2]:
import torch

In [65]:
t = torch.tensor([[[1, 0, -1],[0, 0, 0],[0, 1, 0]],[[1, 0, -1],[1, 1, 1],[0, 1, 0]]]).float()

In [71]:
(torch.abs(t)!=1).float().view(-1, 9)

tensor([[ 0.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  1.]])

In [124]:
import torch

In [156]:
pred_v = torch.tensor(
       [[ 6.1700],
        [ 6.1700],
        [ 6.1700]])

target_v = torch.tensor([[-1.],
        [ 1.],
        [ 0.]])


In [157]:
pred_p = torch.tensor([[ 0.1256,  0.1375,  0.1200,  0.1661,  0.0000,  0.1235,  0.0000,
          0.1587,  0.1686],
        [ 0.0000,  0.3311,  0.2859,  0.0000,  0.0000,  0.0000,  0.0000,
          0.3830,  0.0000],
        [ 0.1218,  0.1333,  0.1165,  0.1616,  0.0000,  0.0000,  0.1447,
          0.1564,  0.1655]])
target_p = torch.tensor([[ 0.3684,  0.1228,  0.1053,  0.0877,  0.0000,  0.1228,  0.0000,
          0.1053,  0.0877],
        [ 0.0000,  0.4136,  0.2408,  0.0000,  0.0000,  0.0000,  0.0000,
          0.3455,  0.0000],
        [ 0.1228,  0.1228,  0.3158,  0.1404,  0.0000,  0.0000,  0.1053,
          0.1053,  0.0877]])


In [158]:
pred_v, pred_p, target_v, target_p

(tensor([[ 6.1700],
         [ 6.1700],
         [ 6.1700]]),
 tensor([[ 0.1256,  0.1375,  0.1200,  0.1661,  0.0000,  0.1235,  0.0000,
           0.1587,  0.1686],
         [ 0.0000,  0.3311,  0.2859,  0.0000,  0.0000,  0.0000,  0.0000,
           0.3830,  0.0000],
         [ 0.1218,  0.1333,  0.1165,  0.1616,  0.0000,  0.0000,  0.1447,
           0.1564,  0.1655]]),
 tensor([[-1.],
         [ 1.],
         [ 0.]]),
 tensor([[ 0.3684,  0.1228,  0.1053,  0.0877,  0.0000,  0.1228,  0.0000,
           0.1053,  0.0877],
         [ 0.0000,  0.4136,  0.2408,  0.0000,  0.0000,  0.0000,  0.0000,
           0.3455,  0.0000],
         [ 0.1228,  0.1228,  0.3158,  0.1404,  0.0000,  0.0000,  0.1053,
           0.1053,  0.0877]]))

In [167]:
def loss1 (pred_v, pred_p, target_v, target_p):
    
    value_error = (target_v.float() - torch.transpose(pred_v,0,1))**2
    #policy_error = (target_p.float()*pred_p.log()).sum(1)
    print (value_error)
    return (value_error - policy_error).mean()


In [173]:
loss1 (pred_v, pred_p, target_v, target_p)

tensor([[ 51.4089,  51.4089,  51.4089],
        [ 26.7289,  26.7289,  26.7289],
        [ 38.0689,  38.0689,  38.0689]])


tensor(40.4300)

In [203]:
def loss_function(pred_v, pred_p, target_v, target_p):
        
        #print ("pred_v = {}".format(pred_v))
        #print ("target_v = {}".format(target_v))
        
        value_loss = ((pred_v - target_v)**2).sum()
        print (value_loss)
        #print ("mean value_loss = {}".format(value_loss))
        
        #print ("pred_p = {}".format(pred_p))
        #print ("target_p = {}".format(target_p))
        
        loglist = torch.where(pred_p > 0, torch.log(pred_p) * target_p, torch.tensor(0.0))
        print (loglist)
        policy_loss = torch.sum(loglist)
        
        print ("policy loss = {}".format(policy_loss))
        constant_list = torch.where(target_p > 0 , torch.log(target_p) * target_p, torch.tensor(0.0))
        constant = torch.sum(constant_list)
        print ("constant = {}".format(constant))
        loss = value_loss - policy_loss + constant
        
        print (loss)
        #print (value_loss, -policy_loss, constant, loss)
        return loss
    

In [204]:
loss_function(pred_v, pred_p, target_v, target_p)

tensor(116.2067)
tensor([[-0.7643, -0.2437, -0.2233, -0.1574,  0.0000, -0.2568,  0.0000,
         -0.1938, -0.1561],
        [ 0.0000, -0.4572, -0.3015,  0.0000,  0.0000,  0.0000,  0.0000,
         -0.3316,  0.0000],
        [-0.2585, -0.2475, -0.6789, -0.2559,  0.0000,  0.0000, -0.2036,
         -0.1954, -0.1578]])
policy loss = -5.0832061767578125
constant = -4.701290607452393
tensor(116.5886)


tensor(116.5886)

AttributeError: module 'torch' has no attribute 'finfo'

In [188]:
loss2 (pred_v, target_v)

tensor(38.7356)

In [189]:
value_loss = ((pred_v - target_v)**2).mean()

In [190]:
value_loss

tensor(38.7356)

In [207]:
value_loss.finfo(torch.float32).eps

AttributeError: 'Tensor' object has no attribute 'finfo'